# Generated by Django 5.0.3 on 2024-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='text',
            field=models.TextField(default='', verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(default='Untitled', max_length=100, verbose_name='عنوان'),
        ),
    ]
