# Generated by Django 5.0.3 on 2024-03-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_contactinfo_options_remove_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={},
        ),
    ]
