# Generated by Django 5.0.3 on 2024-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='text',
            field=models.TextField(default='', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(default='Untitled', max_length=100, verbose_name='title'),
        ),
    ]
